version: '3'

services:
  # MySQL Database
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sucodemorango4
      MYSQL_DATABASE: forcompany
      MYSQL_USER: root
    ports:
      - "4444:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Node.js (Express) Application
  node-app:
    container_name: node-app
    build:
      context: ./server
    ports:
      - "4004:4000"
    depends_on:
      - mysql-db

  # React (Next.js) Application
  react-app:
    container_name: react-app
    build:
      context: ./client
    ports:
      - "3004:3000"
    depends_on:
      - node-app

volumes:
  mysql-data:
